title: BLog
description: >-
  ぼちぼち書いていくつもりです.
lang: ja
baseurl: ""
url: "https://Eivy.github.io"
twitter_username: eivy_m
github_username:  Eivy
timezone: Japan/Tokyo
google_analytics: UA-113621882-1
disqus:
  shortname: https-eivy-github-com
future: true

# Theme settings
minima:
  date_format: "%Y/%m/%d %H:%M"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
